### ISSUE TITLE
不要在代码中实现composer的依赖声明功能

### ISSUE THREAD

**Issue by shellus** [PuShaoWei/MangoCawler#1]
https://github.com/PuShaoWei/MangoCawler/blob/master/index.php#L65

php版本限制、扩展要求，这些可以在`composer.json`里面声明就行了。

**Comment by m9rco** [comment]
🙏好的 ,谢谢祥哥

**Comment by shellus** [comment]
虽然你在https://github.com/PuShaoWei/MangoCawler/commit/473c555088ba276275e0152e2eee333d1c838669
这个分之删除了vendor文件夹。但是实际上，这些文件还是存在于你的这个git仓库

这会让你的git clone命令很慢。

如果想解决，就必须新建一个空白分支，然后把主分支变基过去。然后删除主分支，然后把空百分之重命名成主分支。就好了。不过这样会丢掉你的所有提交记录。

**Comment by m9rco** [comment]
Thank you XIANG Brother

**Comment by m9rco** [comment]
那有什么方法可以做的更优雅呢

**Comment by shellus** [comment]
办法是有的。就是有些麻烦。

你必须重演历史。

因为git是时间线。你无法删除时间历史上的片段。

重演历史的办法是：

...

**Comment by m9rco** [comment]
哈哈
